Repository seoul-night/sodam-server, pull requests merged in 2024-08, with the labels that each got.

#13 친구 추가 시 count +1, 친구 삭제 시 -1 되도록 수정
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
Labels: fix, 🟡 보통

#16 Feat/14 friend list
  src/main/java/growthook/org/bamgang/family/service/FamilyService.java
  src/main/java/growthook/org/bamgang/members/controller/MemberController.java
  src/main/java/growthook/org/bamgang/members/domain/Member.java
  src/main/java/growthook/org/bamgang/members/dto/response/GetMemberResponseDto.java
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
Labels: feat, 🔴 긴급

#18 Fix/17 member response
  src/main/java/growthook/org/bamgang/members/dto/response/GetMemberResponseDto.java
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
Labels: fix, 🔴 긴급

#19 feat:#15-챗봇 기능 구현 완료
  src/main/java/growthook/org/bamgang/chatbot/controller/ChatbotController.java
  src/main/java/growthook/org/bamgang/chatbot/dto/request/MessageRequest.java
  src/main/java/growthook/org/bamgang/chatbot/dto/request/SessionRequest.java
  src/main/java/growthook/org/bamgang/chatbot/dto/response/MessageResponse.java
  src/main/java/growthook/org/bamgang/chatbot/entity/Chatbot.java
  src/main/java/growthook/org/bamgang/chatbot/repository/ChatbotRepository.java
  src/main/java/growthook/org/bamgang/chatbot/service/ChatbotService.java
Labels: feat, 🔴 긴급
